"""Sample API response data for tests."""

import datetime

from custom_components.subaru.const import (
    API_GEN_1,
    API_GEN_2,
    API_GEN_3,
    VEHICLE_API_GEN,
    VEHICLE_CLIMATE,
    VEHICLE_CLIMATE_SELECTED_PRESET,
    VEHICLE_HAS_EV,
    VEHICLE_HAS_LOCK_STATUS,
    VEHICLE_HAS_POWER_WINDOWS,
    VEHICLE_HAS_REMOTE_SERVICE,
    VEHICLE_HAS_REMOTE_START,
    VEHICLE_HAS_SAFETY_SERVICE,
    VEHICLE_HAS_SUNROOF,
    VEHICLE_HAS_TPMS,
    VEHICLE_HEALTH,
    VEHICLE_MODEL_NAME,
    VEHICLE_MODEL_YEAR,
    VEHICLE_NAME,
    VEHICLE_STATUS,
    VEHICLE_VIN,
)

TEST_VIN_1_G1 = "JF2ABCDE6L0000001"
TEST_VIN_2_EV = "JF2ABCDE6L0000002"
TEST_VIN_3_G3 = "JF2ABCDE6L0000003"


VEHICLE_DATA = {
    TEST_VIN_1_G1: {
        VEHICLE_VIN: TEST_VIN_1_G1,
        VEHICLE_NAME: "test_vehicle_1",
        VEHICLE_MODEL_YEAR: "2017",
        VEHICLE_MODEL_NAME: "Outback",
        VEHICLE_HAS_EV: False,
        VEHICLE_API_GEN: API_GEN_1,
        VEHICLE_HAS_LOCK_STATUS: False,
        VEHICLE_HAS_REMOTE_START: True,
        VEHICLE_HAS_REMOTE_SERVICE: True,
        VEHICLE_HAS_SAFETY_SERVICE: False,
        VEHICLE_HAS_POWER_WINDOWS: False,
        VEHICLE_HAS_SUNROOF: False,
        VEHICLE_HAS_TPMS: False,
    },
    TEST_VIN_2_EV: {
        VEHICLE_VIN: TEST_VIN_2_EV,
        VEHICLE_NAME: "test_vehicle_2",
        VEHICLE_MODEL_YEAR: "2019",
        VEHICLE_MODEL_NAME: "Crosstrek",
        VEHICLE_HAS_EV: True,
        VEHICLE_API_GEN: API_GEN_2,
        VEHICLE_HAS_LOCK_STATUS: True,
        VEHICLE_HAS_REMOTE_START: True,
        VEHICLE_HAS_REMOTE_SERVICE: True,
        VEHICLE_HAS_SAFETY_SERVICE: True,
        VEHICLE_HAS_POWER_WINDOWS: False,
        VEHICLE_HAS_SUNROOF: False,
        VEHICLE_HAS_TPMS: True,
    },
    TEST_VIN_3_G3: {
        VEHICLE_VIN: TEST_VIN_3_G3,
        VEHICLE_NAME: "test_vehicle_3",
        VEHICLE_MODEL_YEAR: "2022",
        VEHICLE_MODEL_NAME: "Ascent",
        VEHICLE_HAS_EV: False,
        VEHICLE_API_GEN: API_GEN_3,
        VEHICLE_HAS_LOCK_STATUS: True,
        VEHICLE_HAS_REMOTE_START: True,
        VEHICLE_HAS_REMOTE_SERVICE: True,
        VEHICLE_HAS_SAFETY_SERVICE: True,
        VEHICLE_HAS_POWER_WINDOWS: True,
        VEHICLE_HAS_SUNROOF: True,
        VEHICLE_HAS_TPMS: True,
    },
}

VEHICLE_STATUS_EV = {
    VEHICLE_CLIMATE_SELECTED_PRESET: None,
    VEHICLE_CLIMATE: [
        {
            "name": "Auto",
            "runTimeMinutes": "10",
            "climateZoneFrontTemp": "74",
            "climateZoneFrontAirMode": "AUTO",
            "climateZoneFrontAirVolume": "AUTO",
            "outerAirCirculation": "auto",
            "heatedRearWindowActive": "false",
            "airConditionOn": "false",
            "heatedSeatFrontLeft": "off",
            "heatedSeatFrontRight": "off",
            "startConfiguration": "START_ENGINE_ALLOW_KEY_IN_IGNITION",
            "canEdit": "true",
            "disabled": "false",
            "vehicleType": "gas",
            "presetType": "subaruPreset",
        },
        {
            "name": "Full Cool",
            "runTimeMinutes": "10",
            "climateZoneFrontTemp": "60",
            "climateZoneFrontAirMode": "feet_face_balanced",
            "climateZoneFrontAirVolume": "7",
            "airConditionOn": "true",
            "heatedSeatFrontLeft": "OFF",
            "heatedSeatFrontRight": "OFF",
            "heatedRearWindowActive": "false",
            "outerAirCirculation": "outsideAir",
            "startConfiguration": "START_ENGINE_ALLOW_KEY_IN_IGNITION",
            "canEdit": "true",
            "disabled": "true",
            "vehicleType": "gas",
            "presetType": "subaruPreset",
        },
        {
            "name": "Full Heat",
            "runTimeMinutes": "10",
            "climateZoneFrontTemp": "85",
            "climateZoneFrontAirMode": "feet_window",
            "climateZoneFrontAirVolume": "7",
            "airConditionOn": "false",
            "heatedSeatFrontLeft": "high_heat",
            "heatedSeatFrontRight": "high_heat",
            "heatedRearWindowActive": "true",
            "outerAirCirculation": "outsideAir",
            "startConfiguration": "START_ENGINE_ALLOW_KEY_IN_IGNITION",
            "canEdit": "true",
            "disabled": "true",
            "vehicleType": "gas",
            "presetType": "subaruPreset",
        },
        {
            "name": "Full Cool",
            "runTimeMinutes": "10",
            "climateZoneFrontTemp": "60",
            "climateZoneFrontAirMode": "feet_face_balanced",
            "climateZoneFrontAirVolume": "7",
            "airConditionOn": "true",
            "heatedSeatFrontLeft": "OFF",
            "heatedSeatFrontRight": "OFF",
            "heatedRearWindowActive": "false",
            "outerAirCirculation": "outsideAir",
            "startConfiguration": "START_CLIMATE_CONTROL_ONLY_ALLOW_KEY_IN_IGNITION",
            "canEdit": "true",
            "disabled": "true",
            "vehicleType": "phev",
            "presetType": "subaruPreset",
        },
        {
            "name": "Full Heat",
            "runTimeMinutes": "10",
            "climateZoneFrontTemp": "85",
            "climateZoneFrontAirMode": "feet_window",
            "climateZoneFrontAirVolume": "7",
            "airConditionOn": "false",
            "heatedSeatFrontLeft": "high_heat",
            "heatedSeatFrontRight": "high_heat",
            "heatedRearWindowActive": "true",
            "outerAirCirculation": "outsideAir",
            "startConfiguration": "START_CLIMATE_CONTROL_ONLY_ALLOW_KEY_IN_IGNITION",
            "canEdit": "true",
            "disabled": "true",
            "vehicleType": "phev",
            "presetType": "subaruPreset",
        },
    ],
    VEHICLE_STATUS: {
        "AVG_FUEL_CONSUMPTION": 51.1,
        "DISTANCE_TO_EMPTY_FUEL": 170,
        "DOOR_BOOT_LOCK_STATUS": "UNKNOWN",
        "DOOR_BOOT_POSITION": "CLOSED",
        "DOOR_ENGINE_HOOD_POSITION": "CLOSED",
        "DOOR_FRONT_LEFT_POSITION": "CLOSED",
        "DOOR_FRONT_RIGHT_POSITION": "CLOSED",
        "DOOR_REAR_LEFT_POSITION": "CLOSED",
        "DOOR_REAR_RIGHT_POSITION": None,
        "EV_CHARGER_STATE_TYPE": "CHARGING",
        "EV_CHARGE_SETTING_AMPERE_TYPE": "MAXIMUM",
        "EV_CHARGE_VOLT_TYPE": "CHARGE_LEVEL_1",
        "EV_DISTANCE_TO_EMPTY": 4,
        "EV_IS_PLUGGED_IN": "UNLOCKED_CONNECTED",
        "EV_STATE_OF_CHARGE_MODE": "EV_MODE",
        "EV_STATE_OF_CHARGE_PERCENT": 20,
        "EV_TIME_TO_FULLY_CHARGED_UTC": datetime.datetime(
            2024, 1, 2, 17, 20, 15, tzinfo=datetime.timezone.utc
        ),
        "LAST_UPDATED_DATE": "2024-01-02T12:20:15.000+0000",
        "LATITUDE": 40.0,
        "LOCATION_VALID": True,
        "LOCK_BOOT_STATUS": "UNLOCKED",
        "LOCK_FRONT_LEFT_STATUS": "LOCKED",
        "LOCK_FRONT_RIGHT_STATUS": "LOCKED",
        "LOCK_REAR_LEFT_STATUS": "LOCKED",
        "LOCK_REAR_RIGHT_STATUS": "LOCKED",
        "LONGITUDE": -100.0,
        "ODOMETER": 43265,
        "TIMESTAMP": datetime.datetime(
            2024, 1, 2, 12, 20, 15, tzinfo=datetime.timezone.utc
        ),
        "TRANSMISSION_MODE": "UNKNOWN",
        "TYRE_PRESSURE_FRONT_LEFT": 0,
        "TYRE_PRESSURE_FRONT_RIGHT": 31.9,
        "TYRE_PRESSURE_REAR_LEFT": 32.6,
        "TYRE_PRESSURE_REAR_RIGHT": None,
        "VEHICLE_STATE_TYPE": "IGNITION_OFF",
    },
    VEHICLE_HEALTH: {
        "FEATURES": {
            "ABS_MIL": {"ISTROUBLE": False, "ONDATE": None},
            "AHBL_MIL": {"ISTROUBLE": False, "ONDATE": None},
            "ATF_MIL": {"ISTROUBLE": False, "ONDATE": None},
            "AWD_MIL": {"ISTROUBLE": False, "ONDATE": None},
            "BSDRCT_MIL": {"ISTROUBLE": False, "ONDATE": None},
            "CEL_MIL": {"ISTROUBLE": False, "ONDATE": None},
            "EBD_MIL": {"ISTROUBLE": False, "ONDATE": None},
            "EOL_MIL": {"ISTROUBLE": False, "ONDATE": None},
            "EPAS_MIL": {"ISTROUBLE": False, "ONDATE": None},
            "EPB_MIL": {"ISTROUBLE": False, "ONDATE": None},
            "ESS_MIL": {"ISTROUBLE": False, "ONDATE": None},
            "HEVCM_MIL": {"ISTROUBLE": False, "ONDATE": None},
            "HEV_MIL": {"ISTROUBLE": False, "ONDATE": None},
            "OPL_MIL": {"ISTROUBLE": False, "ONDATE": None},
            "RAB_MIL": {"ISTROUBLE": False, "ONDATE": None},
            "SRS_MIL": {"ISTROUBLE": False, "ONDATE": None},
            "TEL_MIL": {"ISTROUBLE": False, "ONDATE": None},
            "TPMS_MIL": {"ISTROUBLE": False, "ONDATE": None},
            "VDC_MIL": {"ISTROUBLE": False, "ONDATE": None},
            "WASH_MIL": {"ISTROUBLE": True, "ONDATE": 1662157865000},
        },
        "ISTROUBLE": True,
        "RECOMMENDED_TIRE_PRESSURE": {"FRONT_TIRES": 36, "REAR_TIRES": 35},
    },
}


VEHICLE_STATUS_G3 = {
    VEHICLE_STATUS: {
        "AVG_FUEL_CONSUMPTION": 51.1,
        "DISTANCE_TO_EMPTY_FUEL": 170,
        "DOOR_BOOT_POSITION": "CLOSED",
        "DOOR_ENGINE_HOOD_POSITION": "CLOSED",
        "DOOR_FRONT_LEFT_POSITION": "CLOSED",
        "DOOR_FRONT_RIGHT_POSITION": "CLOSED",
        "DOOR_REAR_LEFT_POSITION": "CLOSED",
        "DOOR_REAR_RIGHT_POSITION": "CLOSED",
        "EV_CHARGER_STATE_TYPE": "CHARGING",
        "EV_CHARGE_SETTING_AMPERE_TYPE": "MAXIMUM",
        "EV_CHARGE_VOLT_TYPE": "CHARGE_LEVEL_1",
        "EV_DISTANCE_TO_EMPTY": 4,
        "EV_IS_PLUGGED_IN": "UNLOCKED_CONNECTED",
        "EV_STATE_OF_CHARGE_MODE": "EV_MODE",
        "EV_STATE_OF_CHARGE_PERCENT": 20,
        "EV_TIME_TO_FULLY_CHARGED_UTC": datetime.datetime(
            2024, 1, 2, 17, 20, 15, tzinfo=datetime.timezone.utc
        ),
        "LAST_UPDATED_DATE": "2024-01-02T12:20:15.000+0000",
        "LATITUDE": 40.0,
        "LOCATION_VALID": True,
        "LONGITUDE": -100.0,
        "LOCK_BOOT_STATUS": "LOCKED",
        "LOCK_FRONT_LEFT_STATUS": "LOCKED",
        "LOCK_FRONT_RIGHT_STATUS": "LOCKED",
        "LOCK_REAR_LEFT_STATUS": "LOCKED",
        "LOCK_REAR_RIGHT_STATUS": "LOCKED",
        "ODOMETER": 1234,
        "TIMESTAMP": datetime.datetime(
            2024, 1, 2, 12, 20, 15, tzinfo=datetime.timezone.utc
        ),
        "TRANSMISSION_MODE": "UNKNOWN",
        "TYRE_PRESSURE_FRONT_LEFT": 0,
        "TYRE_PRESSURE_FRONT_RIGHT": 31.9,
        "TYRE_PRESSURE_REAR_LEFT": 32.6,
        "TYRE_PRESSURE_REAR_RIGHT": None,
        "VEHICLE_STATE_TYPE": "IGNITION_OFF",
        "WINDOW_BACK_STATUS": "OPEN",
        "WINDOW_FRONT_LEFT_STATUS": "CLOSE",
        "WINDOW_FRONT_RIGHT_STATUS": "OPEN",
        "WINDOW_REAR_LEFT_STATUS": "OPEN",
        "WINDOW_REAR_RIGHT_STATUS": "OPEN",
        "WINDOW_SUNROOF_STATUS": "OPEN",
    },
}

EXPECTED_STATE_EV_IMPERIAL = {
    "AVG_FUEL_CONSUMPTION": "51.1",
    "DISTANCE_TO_EMPTY_FUEL": "170",
    "DOOR_BOOT_POSITION": "CLOSED",
    "DOOR_ENGINE_HOOD_POSITION": "CLOSED",
    "DOOR_FRONT_LEFT_POSITION": "CLOSED",
    "DOOR_FRONT_RIGHT_POSITION": "CLOSED",
    "DOOR_REAR_LEFT_POSITION": "CLOSED",
    "DOOR_REAR_RIGHT_POSITION": "CLOSED",
    "EV_CHARGER_STATE_TYPE": "CHARGING",
    "EV_CHARGE_SETTING_AMPERE_TYPE": "MAXIMUM",
    "EV_CHARGE_VOLT_TYPE": "CHARGE_LEVEL_1",
    "EV_DISTANCE_TO_EMPTY": "4",
    "EV_IS_PLUGGED_IN": "UNLOCKED_CONNECTED",
    "EV_STATE_OF_CHARGE_MODE": "EV_MODE",
    "EV_STATE_OF_CHARGE_PERCENT": "20",
    "EV_TIME_TO_FULLY_CHARGED_UTC": "2024-01-02T17:20:15+00:00",
    "LAST_UPDATED_DATE": "2024-01-02T12:20:15+00:00",
    "LATITUDE": 40.0,
    "LOCATION_VALID": True,
    "LONGITUDE": -100.0,
    "ODOMETER": "1234",
    "TIMESTAMP": "2024-01-02T12:20:15+00:00",
    "TRANSMISSION_MODE": "UNKNOWN",
    "TYRE_PRESSURE_FRONT_LEFT": "0",
    "TYRE_PRESSURE_FRONT_RIGHT": "31.9",
    "TYRE_PRESSURE_REAR_LEFT": "32.6",
    "TYRE_PRESSURE_REAR_RIGHT": "unknown",
    "VEHICLE_STATE_TYPE": "IGNITION_OFF",
}

EXPECTED_STATE_EV_METRIC = {
    "AVG_FUEL_CONSUMPTION": "4.6",
    "DISTANCE_TO_EMPTY_FUEL": "274",
    "DOOR_BOOT_POSITION": "CLOSED",
    "DOOR_ENGINE_HOOD_POSITION": "CLOSED",
    "DOOR_FRONT_LEFT_POSITION": "CLOSED",
    "DOOR_FRONT_RIGHT_POSITION": "CLOSED",
    "DOOR_REAR_LEFT_POSITION": "CLOSED",
    "DOOR_REAR_RIGHT_POSITION": "CLOSED",
    "EV_CHARGER_STATE_TYPE": "CHARGING",
    "EV_CHARGE_SETTING_AMPERE_TYPE": "MAXIMUM",
    "EV_CHARGE_VOLT_TYPE": "CHARGE_LEVEL_1",
    "EV_DISTANCE_TO_EMPTY": "6",
    "EV_IS_PLUGGED_IN": "UNLOCKED_CONNECTED",
    "EV_STATE_OF_CHARGE_MODE": "EV_MODE",
    "EV_STATE_OF_CHARGE_PERCENT": "20",
    "EV_TIME_TO_FULLY_CHARGED_UTC": "2024-01-02T17:20:15+00:00",
    "LAST_UPDATED_DATE": "2024-01-02T12:20:15+00:00",
    "LATITUDE": 40.0,
    "LOCATION_VALID": True,
    "LONGITUDE": -100.0,
    "ODOMETER": "69628",
    "TIMESTAMP": "2024-01-02T12:20:15+00:00",
    "TRANSMISSION_MODE": "UNKNOWN",
    "TYRE_PRESSURE_FRONT_LEFT": "0",
    "TYRE_PRESSURE_FRONT_RIGHT": "219.9",
    "TYRE_PRESSURE_REAR_LEFT": "224.8",
    "TYRE_PRESSURE_REAR_RIGHT": "unknown",
    "VEHICLE_STATE_TYPE": "IGNITION_OFF",
}

EXPECTED_STATE_EV_UNAVAILABLE = {
    "AVG_FUEL_CONSUMPTION": "unavailable",
    "DISTANCE_TO_EMPTY_FUEL": "unavailable",
    "EV_CHARGER_STATE_TYPE": "unavailable",
    "EV_CHARGE_SETTING_AMPERE_TYPE": "unavailable",
    "EV_CHARGE_VOLT_TYPE": "unavailable",
    "EV_DISTANCE_TO_EMPTY": "unavailable",
    "EV_IS_PLUGGED_IN": "unavailable",
    "EV_STATE_OF_CHARGE_MODE": "unavailable",
    "EV_STATE_OF_CHARGE_PERCENT": "unavailable",
    "EV_TIME_TO_FULLY_CHARGED": "unavailable",
    "EV_TIME_TO_FULLY_CHARGED_UTC": "unavailable",
    "EV_VEHICLE_TIME_DAYOFWEEK": "unavailable",
    "EV_VEHICLE_TIME_HOUR": "unavailable",
    "EV_VEHICLE_TIME_MINUTE": "unavailable",
    "EV_VEHICLE_TIME_SECOND": "unavailable",
    "ODOMETER": "unavailable",
    "POSITION_HEADING_DEGREE": "unavailable",
    "POSITION_SPEED_KMPH": "unavailable",
    "POSITION_TIMESTAMP": "unavailable",
    "TIMESTAMP": "unavailable",
    "TRANSMISSION_MODE": "unavailable",
    "TYRE_PRESSURE_FRONT_LEFT": "unavailable",
    "TYRE_PRESSURE_FRONT_RIGHT": "unavailable",
    "TYRE_PRESSURE_REAR_LEFT": "unavailable",
    "TYRE_PRESSURE_REAR_RIGHT": "unavailable",
    "VEHICLE_STATE_TYPE": "unavailable",
    "heading": "unavailable",
    "latitude": "unavailable",
    "longitude": "unavailable",
    "DOOR_BOOT_POSITION": "unavailable",
    "DOOR_ENGINE_HOOD_POSITION": "unavailable",
    "DOOR_FRONT_LEFT_POSITION": "unavailable",
    "DOOR_FRONT_RIGHT_POSITION": "unavailable",
    "DOOR_REAR_LEFT_POSITION": "unavailable",
    "DOOR_REAR_RIGHT_POSITION": "unavailable",
}

EXPECTED_STATE_EV_BINARY_SENSORS = {
    "DOOR_BOOT_POSITION": "off",
    "DOOR_ENGINE_HOOD_POSITION": "off",
    "EV_IS_PLUGGED_IN": "on",
    "EV_CHARGER_STATE_TYPE": "on",
    "WINDOW_FRONT_LEFT_STATUS": None,
    "WINDOW_FRONT_RIGHT_STATUS": None,
    "WINDOW_REAR_LEFT_STATUS": None,
    "WINDOW_REAR_RIGHT_STATUS": None,
    "WINDOW_SUNROOF_STATUS": None,
    "VEHICLE_STATE_TYPE": "off",
    "DOOR_FRONT_LEFT_POSITION": "off",
    "DOOR_FRONT_RIGHT_POSITION": "off",
    "DOOR_REAR_LEFT_POSITION": "off",
    "DOOR_REAR_RIGHT_POSITION": None,
}
