# Describes the format for available services for subaru
lights:
  description: >
    Flash the lights of the vehicle. The vehicle is identified via the vin
    (see below). This service is deprecated and will be removed - Use button service instead.
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: JF2ABCDE6L0000001

lights_stop:
  description: >
    Stop flashing the lights of the vehicle. The vehicle is identified via the vin
    (see below). This service is deprecated and will be removed - Use button service instead.
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: JF2ABCDE6L0000001

horn:
  description: >
    Sound the horn of the vehicle. The vehicle is identified via the vin
    (see below). This service is deprecated and will be removed - Use button service instead.
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: JF2ABCDE6L0000001

horn_stop:
  description: >
    Stop sounding the horn of the vehicle. The vehicle is identified via the vin
    (see below). This service is deprecated and will be removed - Use button service instead.
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: JF2ABCDE6L0000001

remote_stop:
  description: >
    Stop the engine and climate control of the vehicle. The vehicle is identified via the vin
    (see below). This service is deprecated and will be removed - Use button service instead.
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: JF2ABCDE6L0000001

charge_start:
  description: >
    Starts EV charging. This cannot be stopped remotely. The vehicle is identified via the vin
    (see below). This service is deprecated and will be removed - Use button service instead.
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: JF2ABCDE6L0000001

update:
  description: >
    Sends request to vehicle to update data. The vehicle is identified via the vin
    (see below). This service is deprecated and will be removed - Use button service instead.
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: JF2ABCDE6L0000001

fetch:
  description: >
    Refreshes data (does not request update from vehicle). The vehicle is identified via the vin
    (see below). This service is deprecated and will be removed - Use button service instead.
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: JF2ABCDE6L0000001

unlock_specific_door:
  name: Unlock Specific Door
  description: Unlocks specified door
  target:
    entity:
      domain: lock
      integration: subaru
  fields:
    door:
      name: Door
      description: "One of the following: 'all', 'driver', 'tailgate'"
      example: driver
      required: true
      selector:
        select:
          options:
            - "all"
            - "driver"
            - "tailgate"

remote_start:
  name: Remote Engine Start
  description: Start the engine and set climate control to desired preset
  fields:
    preset_name:
      name: Climate Preset
      description: Desired climate control preset
      example: Full Heat
      required: true
      selector:
        text:
    device_id:
      name: Car
      description: The device (car) to start
      example: 0cce5d5135ac6459ce620654362e45b8
      required: true
      selector:
        device:
          integration: subaru
          manufacturer: Subaru
      