# Describes the format for available services for subaru
lights:
  description: >
    Flash the lights of the vehicle. The vehicle is identified via the vin
    (see below). This service is deprecated and will be removed - Use button service instead.
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: JF2ABCDE6L0000001

lights_stop:
  description: >
    Stop flashing the lights of the vehicle. The vehicle is identified via the vin
    (see below). This service is deprecated and will be removed - Use button service instead.
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: JF2ABCDE6L0000001

horn:
  description: >
    Sound the horn of the vehicle. The vehicle is identified via the vin
    (see below). This service is deprecated and will be removed - Use button service instead.
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: JF2ABCDE6L0000001

horn_stop:
  description: >
    Stop sounding the horn of the vehicle. The vehicle is identified via the vin
    (see below). This service is deprecated and will be removed - Use button service instead.
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: JF2ABCDE6L0000001

remote_start:
  description: >
    Start the engine and climate control of the vehicle.  Uses the climate control settings saved. The vehicle is identified via
    the vin (see below). This service is deprecated and will be removed - Use button service instead.
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: JF2ABCDE6L0000001
    preset_name:
      description: >
        The name of the climate control preset desired
      example: Full Heat

remote_stop:
  description: >
    Stop the engine and climate control of the vehicle. The vehicle is identified via the vin
    (see below). This service is deprecated and will be removed - Use button service instead.
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: JF2ABCDE6L0000001

charge_start:
  description: >
    Starts EV charging. This cannot be stopped remotely. The vehicle is identified via the vin
    (see below). This service is deprecated and will be removed - Use button service instead.
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: JF2ABCDE6L0000001

update:
  description: >
    Sends request to vehicle to update data. The vehicle is identified via the vin
    (see below). This service is deprecated and will be removed - Use button service instead.
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: JF2ABCDE6L0000001

fetch:
  description: >
    Refreshes data (does not request update from vehicle). The vehicle is identified via the vin
    (see below). This service is deprecated and will be removed - Use button service instead.
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: JF2ABCDE6L0000001

unlock_specific_door:
  name: Unlock Specific Door
  description: Unlocks only the door specified
  target:
    entity:
      domain: lock
      integration: subaru
  fields:
    door:
      name: Door
      description: "One of the following: 'all', 'driver', 'tailgate'"
      example: driver
      required: true
      selector:
        select:
          options:
            - "all"
            - "driver"
            - "tailgate"
