unlock_specific_door:
  name: Unlock specific door
  description: Unlocks specific door(s)
  target:
    entity:
      domain: lock
      integration: subaru
  fields:
    door:
      name: Door
      description: "One of the following: 'all', 'driver', 'tailgate'"
      example: driver
      required: true
      selector:
        select:
          options:
            - "all"
            - "driver"
            - "tailgate"
